#:kivy 1.0.9

<CrazyBotGame>:    
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0
            size: 10, self.height
            
    Label:
        font_size: 40  
        center_x: root.width / 4
        top: root.top - 50
        text: str(root.orient1)
        
    Label:
        font_size: 40  
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: str(root.orient2)